export enum EventTypes {
  UpdatePower = 'update-power',
  UpdateAlert = 'update-alert',
  UpdateTemperature = 'update-temperature',
  UpdateThermostatTemp = 'update-thermostat_temp',

  MqttMessage = 'mqtt-message',

  NewStats = 'stats->new',
  NewStatsEx = 'stats->new-ex',

  WiFiConnect = 'wifi->connect',
  WiFiConnected = 'wifi->connected',
  WiFiNetworkFound = 'wifi->network-found',

  ApplicationReady = 'application->ready',
  ApplicationCreated = 'application->created',
  ApplicationGetDevices = 'application->getDevices',
  ApplicationDeviceCommand = 'application->deviceCommand',
  ApplicationAddDeviceQueue = 'application->addDeviceQueue',
  ApplicationAddScanQueue = 'application->addScanQueue',
  NewEvent = 'application->new-event',
  ApplicationDriverReady = 'application->driverReady',

  DatabaseReady = 'database->ready',
  DatabaseConnected = 'database->connected',
  DatabaseGetAllItems = 'database->getAllItems',
  DatabaseUpdateItem = 'database->updateItem',
  DatabaseUpdateDeviceParams = 'database->updateDeviceParams',
  DatabaseCreateItem = 'database->createItem',
  DatabaseQuery = 'database->query',
  DatabaseUpdate = 'database->update',
  DatabaseQueueQuery = 'database->queueQuery',

  CheckSubDevice = 'check-sub-device',
  Publish = 'publish',
  Notify = 'notify',

  DeviceCreate = 'device->create',
  DeviceUpdate = 'device->update',
  DeviceDone = 'device->done',
  DeviceConnect = 'device->connect',
  DeviceDelete = 'device->delete',
  DeviceDiscover = 'device->discover',
  DeviceCheckSubDevice = 'device->check-sub-device',

  DevicesInit = 'devices->init',
  DevicesFind = 'devices->find',
  DevicesGet = 'devices->get',
  DevicesList = 'devices->list',
  DevicesAdd = 'devices->add',

  UpdateSensor = 'sensor->update',
  RemoveSensor = 'sensor->remove',
  UpdateSensorEx = 'sensor->update-ex',

  ChangedMotion = 'changed_motion',
  ChangedMagnet = 'changed_magnet',
  ChangedMagnetChange = 'changed_magnet_change',
  ChangedPower = 'changed_power',
  ChangedPowerChange = 'changed_power_change',
  ChangedAction = 'changed_action',
  ChangedLeakChange = 'changed_leak_change',
  ChangedInputChange = 'changed_input_change',
  ChangedCounterChange = 'changed_counter_change',
  ChangedPowerLoad = 'changed_power_load',
  ChangedChannel0 = 'changed_channel_0',
  ChangedChannel1 = 'changed_channel_1',
  ChangedChannel = 'changed_channel',
}